<?php
namespace controllers;
use Ubiquity\attributes\items\router\Route;
use Ubiquity\attributes\items\router\Get;
use Ubiquity\attributes\items\router\Post;
/**
 * Controller TodosController
 */
class TodosController extends ControllerBase{

    public function initialize(){
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->menu();
    }

    #[Route(path: "/_default/", name : "home")]
    public function index(){

    }

    #[Post(path: "todos/add", name: "todos.add")]
    public function addElement(){

    }


    #[Get(path: "todos/delete/{index}", name : "todos.delete")]
    public function deleteElement($index){

    }


    #[Post(path: "todos/edit/{index}",name: "todos.edit")]
    public function editElement($index){

    }


    #[Get(path: "todos/loadList/{uniqid}", name: "todos.loadList")]
    public function loadList($uniqid){

    }


    #[Post(path: "todos/loadList", name : "todos.loadListPost")]
    public function loadListFromForm(){

    }


    #[Get(path: "todos/new/{force}", name : "todos.new")]
    public function newlist($force=false){

    }


    #[Get(path: "todos/saveList", name : "todos.save")]
    public function saveList(){

    }

    private function menu(){

        $this->loadView(viewName: 'TodosController/menu.html');

    }

}
